"use client";
import Link from "next/link";
import { ArrowRight, BookOpen, FlaskConical, GraduationCap, Users } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { news } from "@/data/news"; import { events } from "@/data/events"; import { people } from "@/data/people"; import { research } from "@/data/research"; import { courses } from "@/data/courses";
import { CourseCard, CourseModal, EventCard, NewsCard, PersonCard, ResearchCard, SectionTitle } from "@/components/ui";
import type { Course } from "@/data/types";

function Counter({ value, label }: { value: string; label: string }) { const [seen, setSeen] = useState(false); const ref = useRef<HTMLDivElement>(null); useEffect(() => { const observer = new IntersectionObserver(([entry]) => entry.isIntersecting && setSeen(true), { threshold: .2 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, []); return <div ref={ref}><p className="text-3xl font-bold md:text-4xl">{seen ? value : "0"}</p><p className="mt-2 text-sm text-slate-400">{label}</p></div>; }
export default function Home() { const [tab, setTab] = useState<Course["degree"]>("Undergraduate"); const [selected, setSelected] = useState<Course | null>(null); return <>
  <section className="hero-grid overflow-hidden"><div className="container-site grid min-h-[580px] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr]"><div className="fade-in"><p className="eyebrow mb-5">Hanoi University of Science & Technology</p><h1 className="max-w-3xl text-5xl font-bold leading-[1.04] tracking-tight md:text-7xl">Technology with <span className="text-brand">purpose.</span></h1><p className="muted mt-7 max-w-xl text-lg leading-8">School of Information and Communication Technology — a community for ambitious learners, rigorous research and human-centered innovation.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/education" className="rounded-xl bg-brand px-5 py-3 text-sm font-bold text-white shadow-lg shadow-brand/20 transition hover:-translate-y-0.5">Explore programs</Link><Link href="/research" className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold transition hover:border-brand hover:text-brand dark:border-white/20">Discover research</Link></div></div><div className="relative hidden lg:block"><div className="absolute -inset-7 rounded-full bg-brand/10 blur-3xl"/><div className="relative aspect-[.96] overflow-hidden rounded-[2rem] border border-white/30 image-shade shadow-2xl"><img src="https://images.unsplash.com/photo-1516321318423-825f1b3f1f31?auto=format&fit=crop&w=1000&q=85" alt="Students working with technology" className="h-full w-full object-cover opacity-70 mix-blend-screen"/><div className="absolute inset-x-6 bottom-6 rounded-2xl border border-white/20 bg-[#092448]/80 p-5 text-white backdrop-blur"><p className="text-xs font-bold uppercase tracking-[.14em] text-red-200">Education · Research · Innovation</p><p className="mt-2 text-xl font-bold">We shape the technology tomorrow needs.</p></div></div></div></div></section>
  <section className="bg-[#102b4c] text-white"><div className="container-site grid grid-cols-2 gap-8 py-12 md:grid-cols-5"><Counter value="5,500+" label="Students"/><Counter value="180+" label="Faculty members"/><Counter value="16" label="Research labs"/><Counter value="12" label="Programs"/><Counter value="800+" label="Publications / year"/></div></section>
  <section className="container-site section-space"><SectionTitle eyebrow="Latest at SOICT" title="Ideas, people and momentum." text="Follow the stories from our classrooms, labs and wider community." action={{label:"View all news",href:"/news"}}/><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{news.slice(0, 3).map((item, i) => <NewsCard key={item.id} item={item} priority={i === 0}/>)}</div></section>
  <section className="border-y line bg-sky/45 dark:bg-white/[.03]"><div className="container-site section-space"><SectionTitle eyebrow="Research areas" title="Curiosity, pursued with intent." text="Our interdisciplinary groups develop foundational knowledge and solutions for a rapidly changing world." action={{label:"All research", href:"/research"}}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{research.map(item => <ResearchCard key={item.id} item={item}/>)}</div></div></section>
  <section className="container-site section-space"><SectionTitle eyebrow="Education" title="Start building your own path." text="Learn in a challenging, generous environment that connects theory to practice."/><div className="mb-7 flex flex-wrap gap-2">{(["Undergraduate", "Graduate", "PhD"] as Course["degree"][]).map(x => <button key={x} onClick={() => setTab(x)} className={`rounded-full px-4 py-2 text-sm font-bold transition ${tab === x ? "bg-brand text-white" : "surface hover:text-brand"}`}>{x}</button>)}</div><div className="grid gap-5 md:grid-cols-3">{courses.filter(x => x.degree === tab).map(item => <CourseCard key={item.id} item={item} onOpen={setSelected}/>)}</div></section>
  <section className="border-y line"><div className="container-site section-space"><SectionTitle eyebrow="Coming up" title="Meet us around campus." action={{label:"All events", href:"/events"}}/><div className="grid gap-5 lg:grid-cols-3">{events.slice(0,3).map(item => <EventCard item={item} key={item.id}/>)}</div></div></section>
  <section className="container-site section-space"><SectionTitle eyebrow="Our people" title="Learn from people who keep learning." action={{label:"Meet the faculty", href:"/people"}}/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{people.slice(0,4).map(item => <PersonCard key={item.id} item={item}/>)}</div></section>
  <section className="container-site pb-20"><div className="relative overflow-hidden rounded-3xl bg-[#102b4c] px-7 py-14 text-white md:px-14"><div className="absolute -right-14 -top-20 h-72 w-72 rounded-full bg-brand/60 blur-3xl"/><div className="relative max-w-2xl"><p className="eyebrow !text-red-200">The next chapter</p><h2 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">Build the future with technology.</h2><p className="mt-5 max-w-xl leading-7 text-slate-300">Join a school where your questions can become research, your ideas can become products, and your work can reach beyond the classroom.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-ink">Get in touch <ArrowRight size={16}/></Link></div></div></section><CourseModal course={selected} onClose={() => setSelected(null)}/>
 </>; }
