import Link from "next/link";

const educationCards = [
  { title: "EDUCATION PROGRAM", image: "/soict/education.jpg", href: "/education", text: "The school is currently providing more than 20 high-quality training programs under 3 undergraduate systems, MSc and PhD. The programs are well received by the international labor market; and one program has more than 60% of graduates working abroad, particularly. The training programs fall into three main disciplines: Computer Science, Computer Engineering, and Data Science and Artificial Intelligence…" },
  { title: "ENLIGHTENING YOUR DIGITAL FUTURE WITH SOICT", image: "/soict/collaboration.jpg", href: "/education", text: "The School of Information and Communications Technology’s engineer status has crossed the country’s borders, and increasingly proves its quality in the international arena. In the wave of Digital Transformation, choosing to develop the future with SOICT will give you the opportunity to become technology experts, capable of mastering and leading the development of science and technology in the country…" },
];
const collaborationCards = [
  { title: "ACADEMIC COLLABORATION", image: "/soict/academic-collaboration.png", href: "/research", text: "School of Information and Communications Technology has cooperative relationships with many prestigious universities and research institutes in the world. Through cooperation, the University’s students have the opportunity to study and research at partner universities through student exchange scholarships, as well as collaborative research projects. The school cooperates with major universities in Europe, Japan…" },
  { title: "BUSINESS PARTNER", image: "/soict/business-partner.jpg", href: "/research", text: "Training and research are essential in substantive cooperation with the business community. The university is currently maintaining cooperation with a network of more than 130 domestic and foreign IT enterprises, including HEDSPI Supporting Partner Network, a network to support students in enhancing foreign languages and soft skills…" },
];

function ContentCard({ card, collaboration = false }: { card: typeof educationCards[number]; collaboration?: boolean }) { return <article className={`soict-content-card ${collaboration ? "is-collaboration" : ""}`}><Link href={card.href} className="soict-card-image"><img src={card.image} alt="" /></Link><div className="soict-card-copy"><h3>{card.title}</h3><p>{card.text} <Link href={card.href}>(see more)</Link></p></div></article>; }

export default function Home() { return <><section className="soict-hero"><div className="soict-hero-image" /><div className="soict-container soict-hero-content"><div className="soict-hero-card"><h1>Admission</h1><p>Information candidates need to know about admission to education programs of the School….</p><Link href="/education">SEE MORE</Link></div></div></section><div className="soict-red-rule" /><section className="soict-section soict-education"><div className="soict-container"><div className="soict-intro"><h2>EDUCATION – ADMISSION</h2><p>Quacquarelli Symonds Education Organization (United Kingdom) assessed and ranked the quality of training and research of Hanoi University of Science and Technology in the fields it is undertaking in the group of 451 to 500. worldwide (2022), continues to hold the No. 1 position among the public universities in Vietnam.</p></div><div className="soict-card-grid">{educationCards.map(card => <ContentCard key={card.title} card={card} />)}</div></div></section><section className="soict-section soict-collaboration"><div className="soict-container"><div className="soict-intro is-light"><h2>COLLABORATION ACTIVITIES</h2><p>School of Information and Communication Technology always attaches importance to international cooperation activities and business cooperation to improve the quality of teaching, research and technology transfer activities.</p></div><div className="soict-card-grid">{collaborationCards.map(card => <ContentCard key={card.title} card={card} collaboration />)}</div></div></section></>; }
