"use client";
import Link from "next/link";
import { ArrowRight, Bookmark, Check, MapPin, CalendarDays, SearchX } from "lucide-react";
import { useEffect, useState } from "react";
import type { Course, Event, News, Person, Research } from "@/data/types";

export const formatDate = (date: string) => new Intl.DateTimeFormat("en", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${date}T12:00:00`));
export function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="hero-grid border-b line py-18"><div className="container-site py-12"><p className="eyebrow mb-4">{eyebrow}</p><h1 className="max-w-3xl text-4xl font-bold tracking-tight md:text-6xl">{title}</h1><p className="muted mt-5 max-w-2xl text-base leading-7 md:text-lg">{text}</p></div></section>; }
export function SectionTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text?: string; action?: { label: string; href: string } }) { return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-3">{eyebrow}</p><h2 className="text-3xl font-bold tracking-tight md:text-4xl">{title}</h2>{text && <p className="muted mt-3 max-w-xl leading-7">{text}</p>}</div>{action && <Link href={action.href} className="inline-flex items-center gap-2 text-sm font-bold text-brand hover:gap-3">{action.label}<ArrowRight size={16}/></Link>}</div>; }
export function FavoriteButton({ type, id }: { type: "news" | "events"; id: number }) { const key = `soict-favorites-${type}`; const [saved, setSaved] = useState(false); useEffect(() => setSaved(JSON.parse(localStorage.getItem(key) ?? "[]").includes(id)), [key, id]); const toggle = () => { const list: number[] = JSON.parse(localStorage.getItem(key) ?? "[]"); const next = list.includes(id) ? list.filter(item => item !== id) : [...list, id]; localStorage.setItem(key, JSON.stringify(next)); setSaved(next.includes(id)); }; return <button onClick={toggle} aria-label="Save item" className={`rounded-full p-2 transition ${saved ? "bg-brand text-white" : "bg-white/90 text-ink hover:text-brand"}`}><Bookmark size={17} fill={saved ? "currentColor" : "none"}/></button>; }
export function NewsCard({ item, priority = false }: { item: News; priority?: boolean }) { return <article className="surface card-hover overflow-hidden rounded-2xl"><div className="relative h-48 overflow-hidden image-shade"><img loading={priority ? "eager" : "lazy"} src={item.image} alt="" className="h-full w-full object-cover opacity-75 mix-blend-luminosity transition duration-500 hover:scale-105"/><div className="absolute right-3 top-3"><FavoriteButton type="news" id={item.id}/></div></div><div className="p-5"><div className="mb-3 flex items-center gap-2 text-xs"><span className="rounded-full bg-sky px-2.5 py-1 font-bold text-brand dark:bg-brand/20">{item.category}</span><span className="muted">{formatDate(item.date)}</span></div><h3 className="line-clamp-2 text-lg font-bold leading-6"><Link href={`/news/${item.slug}`} className="hover:text-brand">{item.title}</Link></h3><p className="muted mt-3 line-clamp-2 text-sm leading-6">{item.excerpt}</p><Link href={`/news/${item.slug}`} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-brand">Read story <ArrowRight size={15}/></Link></div></article>; }
export function EventCard({ item }: { item: Event }) { return <article className="surface card-hover group rounded-2xl p-5"><div className="flex gap-4"><time className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-brand text-center text-white"><span className="text-xs font-bold uppercase">{new Date(`${item.date}T12:00:00`).toLocaleDateString("en", { month: "short" })}</span><span className="-mt-2 text-xl font-bold">{new Date(`${item.date}T12:00:00`).getDate()}</span></time><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-widest text-brand">{item.category}</p><h3 className="mt-1 text-lg font-bold leading-6"><Link href={`/events/${item.id}`} className="group-hover:text-brand">{item.title}</Link></h3></div></div><p className="muted mt-5 line-clamp-2 text-sm leading-6">{item.description}</p><div className="mt-4 flex items-center justify-between text-xs font-medium text-slate-500 dark:text-slate-400"><span className="flex items-center gap-1"><CalendarDays size={14}/>{item.time}</span><span className="flex items-center gap-1"><MapPin size={14}/>{item.location}</span></div></article>; }
export function PersonCard({ item }: { item: Person }) { return <article className="surface card-hover overflow-hidden rounded-2xl"><div className="h-48 overflow-hidden image-shade"><img loading="lazy" src={item.avatar} alt={item.name} className="h-full w-full object-cover object-top opacity-85"/></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-brand">{item.department}</p><h3 className="mt-2 text-lg font-bold"><Link href={`/people/${item.id}`} className="hover:text-brand">{item.name}</Link></h3><p className="muted mt-1 text-sm">{item.position}</p><div className="mt-4 flex flex-wrap gap-1.5">{item.interests.slice(0, 2).map(x => <span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] dark:bg-white/10" key={x}>{x}</span>)}</div></div></article>; }
export function ResearchCard({ item }: { item: Research }) { return <article className="surface card-hover rounded-2xl p-6"><div className="mb-6 grid h-12 w-12 place-items-center rounded-xl bg-brand text-sm font-black text-white">{item.icon}</div><h3 className="text-xl font-bold">{item.title}</h3><p className="muted mt-3 text-sm leading-6">{item.short}</p><div className="mt-6 flex items-center gap-2 text-xs font-bold text-brand">Explore area <ArrowRight size={15}/></div></article>; }
export function CourseCard({ item, onOpen }: { item: Course; onOpen: (course: Course) => void }) { return <article className="surface card-hover rounded-2xl p-6"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-sky px-3 py-1 text-xs font-bold text-brand dark:bg-brand/20">{item.degree}</span><span className="muted text-xs">{item.duration}</span></div><h3 className="mt-5 text-xl font-bold">{item.name}</h3><p className="muted mt-3 text-sm leading-6">{item.description}</p><div className="my-5 border-t line"/><p className="text-sm"><b>{item.credits}</b> credits</p><button onClick={() => onOpen(item)} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-brand">Program details <ArrowRight size={15}/></button></article>; }
export function EmptyState({ text = "No results found." }: { text?: string }) { return <div className="surface grid min-h-56 place-items-center rounded-2xl p-8 text-center"><div><SearchX className="mx-auto mb-3 text-brand" size={30}/><p className="font-bold">{text}</p><p className="muted mt-1 text-sm">Try changing your keywords or filters.</p></div></div>; }
export function CourseModal({ course, onClose }: { course: Course | null; onClose: () => void }) { if (!course) return null; return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#071528]/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="surface max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl p-6 md:p-8"><button className="float-right text-sm font-bold text-brand" onClick={onClose}>Close</button><p className="eyebrow">{course.degree} · {course.duration}</p><h2 className="mt-3 text-3xl font-bold">{course.name}</h2><p className="muted mt-4 leading-7">{course.description}</p><div className="mt-7 grid gap-6 sm:grid-cols-2"><div><h3 className="font-bold">Curriculum highlights</h3><ul className="mt-3 space-y-2 text-sm">{course.curriculum.map(x => <li className="flex gap-2" key={x}><Check size={16} className="mt-0.5 text-brand"/>{x}</li>)}</ul></div><div><h3 className="font-bold">Career paths</h3><ul className="mt-3 space-y-2 text-sm">{course.careers.map(x => <li className="flex gap-2" key={x}><Check size={16} className="mt-0.5 text-brand"/>{x}</li>)}</ul></div></div></div></div>; }
